# !/bin/sh

./TBLERstats.py -t=BFcompU -l=GBF-PREV,ABF-PREV,GBF-PAD4,ABF-PAD4,HBF-PAD4,SBF-PAD4 GBF-PREV-UNRL.log ABF-PREV-UNRL.log GBF-PAD4-UNRL.log ABF-PAD4-UNRL.log HBF-PAD4-UNRL.log SBF-PAD4-UNRL.log

./TBLERstats.py -t=SCcompU -l=ABF-PREV,ABF-1LAY,ABF-PAD4,SBF-PAD4,ABF-ASC4,SBF-ASC4 ABF-PREV-UNRL.log ABF-1LAY-UNRL.log ABF-PAD4-UNRL.log SBF-PAD4-UNRL.log ABF-ASC4-UNRL.log SBF-ASC4-UNRL.log

./TBLERstats.py -t=BFcompH -l=GBF-PREV,ABF-PREV,GBF-PAD4,ABF-PAD4,HBF-PAD4,SBF-PAD4 GBF-PREV-HARQ.log ABF-PREV-HARQ.log GBF-PAD4-HARQ.log ABF-PAD4-HARQ.log HBF-PAD4-HARQ.log SBF-PAD4-HARQ.log

./TBLERstats.py -t=SCcompH -l=ABF-PREV,ABF-1LAY,ABF-PAD4,SBF-PAD4,ABF-ASC4,SBF-ASC4 ABF-PREV-HARQ.log ABF-1LAY-HARQ.log ABF-PAD4-HARQ.log SBF-PAD4-HARQ.log ABF-ASC4-HARQ.log SBF-ASC4-HARQ.log
