# !/bin/sh

#Beamforming comparison (Unreliable for SINR and BLER, UNRL vs HARQ for total bytes received)
./TRACEstats.py -t=BFcompU -l=GBF-PREV,ABF-PREV,GBF-PAD4,ABF-PAD4,HBF-PAD4,SBF-PAD4 GBF-PREV-UNRL.trace ABF-PREV-UNRL.trace GBF-PAD4-UNRL.trace ABF-PAD4-UNRL.trace HBF-PAD4-UNRL.trace SBF-PAD4-UNRL.trace
./PKTstats.py -t=BFcompU -l=GBF-PREV,ABF-PREV,GBF-PAD4,ABF-PAD4,HBF-PAD4,SBF-PAD4 GBF-PREV-UNRL.log ABF-PREV-UNRL.log GBF-PAD4-UNRL.log ABF-PAD4-UNRL.log HBF-PAD4-UNRL.log SBF-PAD4-UNRL.log
#./TRACEstats.py -t=BFcompH -l=GBF-PREV,ABF-PREV,GBF-PAD4,ABF-PAD4,HBF-PAD4,SBF-PAD4 GBF-PREV-HARQ.trace ABF-PREV-HARQ.trace GBF-PAD4-HARQ.trace ABF-PAD4-HARQ.trace HBF-PAD4-HARQ.trace SBF-PAD4-HARQ.trace
./PKTstats.py -t=BFcompH -l=GBF-PREV,ABF-PREV,GBF-PAD4,ABF-PAD4,HBF-PAD4,SBF-PAD4 GBF-PREV-HARQ.log ABF-PREV-HARQ.log GBF-PAD4-HARQ.log ABF-PAD4-HARQ.log HBF-PAD4-HARQ.log SBF-PAD4-HARQ.log

#Scheduler comparison (Unreliable for SINR and BLER, UNRL vs HARQ for total bytes received)
./TRACEstats.py -t=SCcompU -l=ABF-PREV,ABF-1LAY,ABF-PAD4,SBF-PAD4,ABF-ASC4,SBF-ASC4 ABF-PREV-UNRL.trace ABF-1LAY-UNRL.trace ABF-PAD4-UNRL.trace SBF-PAD4-UNRL.trace ABF-ASC4-UNRL.trace SBF-ASC4-UNRL.trace
./PKTstats.py -t=SCcompU -l=ABF-PREV,ABF-1LAY,ABF-PAD4,SBF-PAD4,ABF-ASC4,SBF-ASC4 ABF-PREV-UNRL.log ABF-1LAY-UNRL.log ABF-PAD4-UNRL.log SBF-PAD4-UNRL.log ABF-ASC4-UNRL.log SBF-ASC4-UNRL.log
#./TRACEstats.py -t=SCcompH -l=ABF-PREV,ABF-1LAY,ABF-PAD4,SBF-PAD4,ABF-ASC4,SBF-ASC4 ABF-PREV-HARQ.trace ABF-1LAY-HARQ.trace ABF-PAD4-HARQ.trace SBF-PAD4-HARQ.trace ABF-ASC4-HARQ.trace SBF-ASC4-HARQ.trace
./PKTstats.py -t=SCcompH -l=ABF-PREV,ABF-1LAY,ABF-PAD4,SBF-PAD4,ABF-ASC4,SBF-ASC4 ABF-PREV-HARQ.log ABF-1LAY-HARQ.log ABF-PAD4-HARQ.log SBF-PAD4-HARQ.log ABF-ASC4-HARQ.log SBF-ASC4-HARQ.log

#TCP comparison (UNRL vs HARQ in same figure for total bytes received only)
# ./TRACEstats.py -t=TCP -l=ABF-SISO-U,ABF-SISO-H,SBF-MIMO-U,SBF-MIMO-H TCP-ABF-PREV-UNRL.trace TCP-ABF-PREV-HARQ.trace TCP-SBF-PAD4-UNRL.trace TCP-SBF-PAD4-HARQ.trace
./PKTstats.py -t=TCP -l=ABF-SISO-U,ABF-SISO-H,SBF-MIMO-U,SBF-MIMO-H TCP-ABF-PREV-UNRL.log TCP-ABF-PREV-HARQ.log TCP-SBF-PAD4-UNRL.log TCP-SBF-PAD4-HARQ.log
